// starter-projects/templates-lab/minimal-island/src/islands/Counter.react.tsx
/** @jsxImportSource react */

import { useState } from 'react';

export default function CounterReact() {
	const [count, setCount] = useState(0);

	return (
		<div>
			<h3>React Counter</h3>
			<p>Count: {count}</p>
			<button onClick={() => setCount(count + 1)}>Increment</button>
			<button onClick={() => setCount(0)}>Reset</button>
		</div>
	);
}

// integration/__fixtures__/static-site-islands/src/islands/Counter.solid.tsx
/** @jsxImportSource solid-js */

import { createSignal } from 'solid-js';

export default function CounterSolid() {
	const [count, setCount] = createSignal(0);

	return (
		<div data-island="solid">
			<h3>Island: Solid</h3>
			<p class="island-status">Solid SSR OK</p>
			<p>Count: {count()}</p>
			<button onClick={() => setCount((c) => c + 1)}>+1</button>
		</div>
	);
}
