// integration/__fixtures__/static-site-islands/src/islands/Counter.preact.tsx
/** @jsxImportSource preact */

import { useState } from 'preact/hooks';

export default function CounterPreact() {
	const [count, setCount] = useState(0);

	return (
		<div data-island="preact">
			<h3>Island: Preact</h3>
			<p className="island-status">Preact SSR OK</p>
			<p>Count: {count}</p>
			<button onClick={() => setCount((c) => c + 1)}>+1</button>
		</div>
	);
}

// integration/__fixtures__/static-site-islands/src/islands/Counter.solid.tsx
/** @jsxImportSource solid-js */

import { createSignal } from 'solid-js';

export default function CounterSolid() {
	const [count, setCount] = createSignal(0);

	return (
		<div data-island="solid">
			<h3>Island: Solid</h3>
			<p class="island-status">Solid SSR OK</p>
			<p>Count: {count()}</p>
			<button onClick={() => setCount((c) => c + 1)}>+1</button>
		</div>
	);
}
