// starter-projects/templates/minimal-server-react-islands/src/islands/Counter.vue
<script setup lang="ts">
import { ref } from 'vue';

let test: string = ref('test');

console.log('VUE');
</script>

<template>
	---
	<!--  -->
	<h2>VUE COUNTER2 11</h2>

	<!-- <button @click="console.log('VUEZ')">VUE GO</button> -->
	<button @click="test = Math.random().toString()">GO</button>
	{{ test }}

	<slot v-pre></slot>:SLOT
	<!--  -->
	---
</template>

// starter-projects/templates/minimal-server-react-islands/src/islands/Counter.solid.tsx
/** @\jsx solid-js */
import { createSignal } from 'solid-js';

// console.log({ Pdsffffffffffff: P });

// console.log({ React });

export default function CounterSolid(params) {
	const [test, setTest] = createSignal(2);

	return (
		<>
			<h2>11 SOLID COUYNTER</h2>
			{JSON.stringify(params)}
			<details></details>
			SLOT:
			<slot />
			:SLOT ---
			<hr />
			{/* <CounterSolid2 /> */}
			{test}
			<button onClick={() => setTest(test() + 5)}>GO</button>
			<hr />
		</>
	);
}

// export function CounterSolid2(params) {
// 	const [a, b] = P.useState('KO');
// 	console.log('PRET');
// 	// P.useEffect(() => {});
// 	return (
// 		<>
// 			{a}
// 			{JSON.stringify(params)}
// 			--- PPPPREACT COUNTER
// 			<details></details>
// 			<button
// 				onClick={() => {
// 					b(Math.random().toString());
// 					console.log('OK');
// 				}}
// 			>
// 				DFDD
// 			</button>
// 		</>
// 	);
// }
