// starter-projects/templates/minimal-server-react-islands/src/islands/Counter.solid.tsx
/** @\jsx solid-js */
import { createSignal } from 'solid-js';

// console.log({ Pdsffffffffffff: P });

// console.log({ React });

export default function CounterSolid(params) {
	const [test, setTest] = createSignal(2);

	return (
		<>
			<h2>11 SOLID COUYNTER</h2>
			{JSON.stringify(params)}
			<details></details>
			SLOT:
			<slot />
			:SLOT ---
			<hr />
			{/* <CounterSolid2 /> */}
			{test}
			<button onClick={() => setTest(test() + 5)}>GO</button>
			<hr />
		</>
	);
}

// export function CounterSolid2(params) {
// 	const [a, b] = P.useState('KO');
// 	console.log('PRET');
// 	// P.useEffect(() => {});
// 	return (
// 		<>
// 			{a}
// 			{JSON.stringify(params)}
// 			--- PPPPREACT COUNTER
// 			<details></details>
// 			<button
// 				onClick={() => {
// 					b(Math.random().toString());
// 					console.log('OK');
// 				}}
// 			>
// 				DFDD
// 			</button>
// 		</>
// 	);
// }

// starter-projects/templates/minimal-server-react-islands/src/islands/Counter.react.tsx
/** @\jsx react-jsx */

import React, { useState, use } from 'react';

// console.log({ React });
console.log(React.version); // ← “18.2.0” (hard-coded in compat)
console.log(React.useId); // undefined until Preact 11
console.log({ use });

export default function CounterReact(params) {
	return (
		<>
			{/* {JSON.stringify(params)} */}
			<h2>111REACT COUNTER </h2>
			<details></details>
			SLOT:
			<slot />
			:SLOT ---
			<hr />
			<SubCh />
			<hr />
			{/* <button
				onClick={() => {
					console.log('OK');
				}}
			>
				CounterReact
			</button> */}
		</>
	);
}

export function SubCh(params) {
	const [a, setA] = useState('KO');
	console.log('PRET');
	// P.useEffect(() => {});
	return (
		<>
			{/* {JSON.stringify(params)} */}
			---
			<data>{a}</data>
			<details></details>
			<button
				onClick={() => {
					setA(Math.random().toString());
					console.log('OK');
				}}
			>
				DFDD
			</button>
		</>
	);
}
